project:
  type: website
  output-dir: docs

website:
  title: "Sophie Vargas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - Hobbies.qmd
      - Résumé.qmd

format:
  html:
    theme: 
      light: yeti
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

