---
title: "Résumé"
---

## Education

University of California, Santa Barbara - Santa Barbara, CA 2024 Bachelor of Science - Environmental Studies

Wildlands Field Studies Program - Ecological Research on Tropical Reefs and Rainforests in Northern Queensland, Australia, Summer of 2023

## Work Experience

### Caselle Lab Intern - UCSB - Fall 2023 and Winter/Spring 2024

Analyze Palmyra BRUV videos under Peter carlson and Jen Caselle

Focus on understanding the ecological relationships between parrotfish herbivory and various spatial scales that impact benthic communities

### Pre-Med Internship in Family Medicine - Healdsburg, CA Summer 2022

Warmly greeted and checked in patients in the front office

Took vital signs

Assessed their complaints

Participated in examinations and discussion of diagnosis

Collaborated on treatment strategies and helped arrange follow-up appointments

### Campo Fina Restaurant Back Waiter - Healdsburg, California - Spring 2019

Efficiently assisted wait staff with cleaning Set and cleared tables Refilled drinks Accommodated guests.

## Special Skills and Attributes

UCSB Women’s Soccer Team - NCAA Division I - 2020-2023

Team player and demonstrated leader, good communication, organizational, and time-management skills.

20 hours a week + games on weekends, occasionally traveling

### Isla Vista Surfrider - Chair of Ocean Friendly Restaurants Committee - 2022-2023

Effectively facilitate weekly meetings and group projects convincing local restaurants in our community to become more sustainable.
